### PR TITLE
Windows build fix

### PR DESCRIPTION
**Pull request by abhijeetkpawar**
Fix for bug #18

### CODE REVIEW

**Comment by nbarbettini** [comment]
@abhijeetkpawar This only sets the environment variable in the context of the current process, right? Does that work when the script is executed by another script (like in your original issue)?

@rchild-okta - did you want to explore dropping `cross-env` in here? Seems like an easy solution.

**Comment by abhijeetkpawar** [comment]
@nbarbettini This solution worked for me. Not sure about any other use case

**Comment by rchild-okta** [comment]
@nbarbettini yeah, I think cross-env would be a good fix for now. Want to submit a PR/work with @bretterer to get it added to the generator?

**Comment by synthmusic** [comment]
I ended up here from the issue in express samples [https://github.com/okta/samples-nodejs-express-4/issues/18](https://github.com/okta/samples-nodejs-express-4/issues/18) as noted by @abhijeetkpawar 

This fix does work for windows specifically building from samples-nodejs-express-4, also unsure of other cases.  Cross-env may be a better solution, but ultimately the bug still exists.

**Comment by nbarbettini** [comment]
Closing in favor of #22. Sorry for the delay, and thanks for helping identify this bug @abhijeetkpawar!

**Comment by nbarbettini** [comment]
BTW, if anyone runs into more build errors on Windows (or other OSes), please open a new issue. We'll fix it! 👍

**Pull request closed without merging**
